[package]
name = "lovecraft"
version = "0.1.0"
authors = ["Geoffroy Couprie <geo.couprie@gmail.com>"]
edition = "2018"
description = "brings back the Lovecraft quotes on panic"
license = "MIT"

[dependencies]
